name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull d29553883/bookmall:latest
    - name: Delete Old docker container
      run: sudo docker rm -f bookmall_container || true     
    - name: Run Docker Container
      run: sudo docker run --name bookmall_container -p 8000:3000 --env-file /home/ubuntu/bookmall/.env -d d29553883/bookmall