name: CI Pipeline

on:
  push:
    branches: [ "use_jwt" ]
  pull_request:
    branches: [ "use_jwt" ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    # 安装 Python 3.9.7 和 Pytest
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.7

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt

    # 運行 Pytest 测试
    - name: Run Pytest tests
      run: pytest
      env:
        PASSWORD: ${{ secrets.ENDPOINT }}
        Endpoint: ${{ secrets.PASSWORD }}


    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image 
      run: docker build -t d29553883/bookmall .
    - name: Push to Dockerhub
      run: docker push d29553883/bookmall