name: CI Pipeline

on:
  push:
    branches: [ "use_jwt" ]
  pull_request:
    branches: [ "use_jwt" ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t d29553883/bookmall .
    - name: Push to Dockerhub
      run: docker push d29553883/bookmall
